name: go-new-gha-test

 
on:
  push:

permissions:
  id-token: write 
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Register Build Artifact
        uses: cloudbees-io-gha/register-build-artifact@v3
        with:
          name: "go-new-gha-test"
          version: "tag0.1"
          url: "020229604682.dkr.ecr.us-east-1.amazonaws.com/throwaway/actions/vulnerable-image:tag0.1"
          cloudbees-url: "https://api.saas-qa.beescloud.com"      
