name: workflow
 
on:
  push:

permissions:
  id-token: write 
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Register Build Artifact
        uses: cloudbees-io-gha/register-build-artifact@v3
        with:
          name: "gha-1"
          version: "tag3.0"
          url: "020229604682.dkr.ecr.us-east-1.amazonaws.com/throwaway/actions/vulnerable-image:tag3.0"
          cloudbees-url: "https://api.saas-qa.beescloud.com"      
